-- ============================================================
-- CODEHERO MASTER INSTALLATION SCRIPT
-- ============================================================
-- Usage: Run this entire script in the Supabase SQL Editor.
-- This sets up the complete database schema, security policies,
-- and admin functions required for the application.

-- 1. ENABLE ROW LEVEL SECURITY (Base)
alter table auth.users enable row level security;

-- 2. PUBLIC TABLES

-- PROFILES
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  email text, -- Added for Admin Panel management
  avatar_svg text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- WORLDS
create table if not exists public.worlds (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  style text, -- 'cyberpunk', 'matrix', etc
  level_range int[] -- e.g. {1, 10}
);
alter table public.worlds enable row level security;
create policy "Worlds are public." on worlds for select using (true);
create policy "Admins can edit worlds." on worlds for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- PHASES
create table if not exists public.phases (
  id bigint generated by default as identity primary key,
  world_id bigint references public.worlds not null,
  title text not null,
  description text,
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.phases enable row level security;
create policy "Phases are public." on phases for select using (true);
create policy "Admins can edit phases." on phases for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- LEVEL TYPES
create table if not exists public.level_types (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text,
  description text,
  color text default '#ffffff',
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.level_types enable row level security;
create policy "Level Types are public." on level_types for select using (true);
create policy "Admins can edit level types." on level_types for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- LEVELS
create table if not exists public.levels (
  id bigint generated by default as identity primary key,
  phase_id bigint references public.phases not null,
  title text not null,
  type text,
  description text,
  map jsonb,
  start_pos jsonb,
  end_pos jsonb,
  perfect_score int,
  hint text,
  start_code jsonb default '[]'::jsonb, -- New: For debugging levels
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.levels enable row level security;
drop policy if exists "Levels are public." on levels;
drop policy if exists "Admins can edit levels." on levels;

create policy "Levels are public." on levels for select using (true);
create policy "Admins can edit levels." on levels for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- ... (Existing Policies) ...

-- UPDATE USER EMAIL ADMIN
-- Drops existing to ensure return type compatibility if signature changes
DROP FUNCTION IF EXISTS public.update_user_email_admin(uuid, text);

CREATE OR REPLACE FUNCTION public.update_user_email_admin(target_user_id uuid, new_email text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Security Check
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Access Denied';
  END IF;

  -- Update Auth (Handles login)
  UPDATE auth.users 
  SET email = new_email, 
      email_confirmed_at = now(),
      updated_at = now() 
  WHERE id = target_user_id;

  -- Update Profile
  UPDATE public.profiles 
  SET email = new_email 
  WHERE id = target_user_id;
END;
$$;

-- Grant permissions for RPCs
grant execute on function public.delete_user_admin to authenticated;
grant execute on function public.update_user_email_admin to authenticated;

-- 4. CLEANUP LEGACY TRIGGERS
-- Ensure the flashing/race-condition causing trigger is gone
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- 5. CONTENT MANAGEMENT (SEED & RESTORE)

-- FUNCTION: RESET LEVEL DATA
-- Allows Admins to restore the original 14 Levels, Worlds, and Phases.
create or replace function public.reset_level_data()
returns void
language plpgsql
security definer
as $$
DECLARE
    p_seq_id bigint;
    p_ori_id bigint;
    p_loop_id bigint;
    p_cond_id bigint;
    p_debug_id bigint;
BEGIN
    -- 1. Security Check
    if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
        raise exception 'Access Denied';
    end if;

    -- HARD RESET: Clear Tables to ensure clean IDs and relationships
    DELETE FROM public.progress;    -- HARD RESET: Clear Tables to ensure clean IDs and relationships
    DELETE FROM public.levels;
    DELETE FROM public.phases;
    DELETE FROM public.level_types; -- Reset types
    DELETE FROM public.worlds;

    -- 0. FIX SEQUENCES (Reset to 1 since tables are empty)
    ALTER SEQUENCE public.worlds_id_seq RESTART WITH 1;
    ALTER SEQUENCE public.phases_id_seq RESTART WITH 1;
    ALTER SEQUENCE public.level_types_id_seq RESTART WITH 1;
    ALTER SEQUENCE public.levels_id_seq RESTART WITH 1;

    -- ============ [START] SEED DATA (COPY FROM ADMIN) ============
    -- NOTE: Select everything between [START] and [END] and replace with the code generated in Admin Panel > Settings

    -- 1. RESTORE LEVEL TYPES
    INSERT INTO public.level_types (id, name, slug, color, description) VALUES
    (1, 'Tutorial', 'tutorial', '#10b981', ''),
    (2, 'Básico', 'basic', '#3b82f6', ''),
    (3, 'Giros', 'turns', '#8b5cf6', ''),
    (4, 'Bucles', 'loops', '#f59e0b', ''),
    (5, 'Condicionales', 'conditionals', '#ec4899', ''),
    (6, 'Portales', 'portals', '#06b6d4', ''),
    (7, 'Debugging', 'debug', '#ef4444', ''),
    (8, 'Boss', 'boss', '#ffffff', '');
    -- Sync Types Seq
    ALTER SEQUENCE public.level_types_id_seq RESTART WITH 9;

    -- 2. RESTORE WORLDS
    INSERT INTO public.worlds (id, title, description, style, level_range) VALUES
    (1, 'Mundo 1: Lógica & Algoritmos', 'Aprende los fundamentos de la programación.', 'cyberpunk', '{0,13}'),
    (2, 'Mundo 2: La Base de Datos', 'Niveles avanzados de reparación (Debugging) y optimización de código.', 'matrix', '{14,20}')
    ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;
    ALTER SEQUENCE public.worlds_id_seq RESTART WITH 3;

    -- 3. RESTORE PHASES
    INSERT INTO public.phases (id, world_id, title, description, order_index) VALUES
    (1, 1, 'Secuenciación', 'Pasos básicos y orden.', 1),
    (2, 1, 'Orientación', 'Giros y movimiento espacial.', 2),
    (3, 1, 'Bucles & Patron', 'Repetición eficiente.', 3),
    (4, 1, 'Estado (Llaves)', 'Condicionales y memoria.', 4),
    (5, 1, 'Lógica Avanzada', 'Portales y retos complejos.', 5),
    (6, 2, 'Reparación (Debugging)', 'El código está roto. ¡Encuentra el error y arréglalo!', 1)
    ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title;
    ALTER SEQUENCE public.phases_id_seq RESTART WITH 7;

    -- 4. RESTORE LEVELS (Total: 19)
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (1, 1, 'El Primer Paso', 'Un algoritmo es una lista de pasos. Diles a tu robot que avance dos veces para llegar a la meta 🚩.', 'Tutorial', '[[1,1,1,1,1],[1,0,0,0,1],[1,2,0,0,1],[1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":3,"y":1}'::jsonb, 2, null, null, '[]'::jsonb, 'Usa dos bloques "Avanzar".', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (2, 1, 'La Ruta Exacta', 'La precisión es clave. Cuenta las casillas: si das pasos de más, chocarás.', 'Básico', '[[1,1,1,1,1,1,1],[1,0,0,0,0,0,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":5,"y":1}'::jsonb, 4, null, null, '[]'::jsonb, 'Cuenta los cuadros. Necesitas 4 pasos exactos.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (3, 2, 'El Giro', 'Girar cambia tu dirección, pero no te mueve. Gira y luego avanza.', 'Giros', '[[1,1,1,1,1],[1,1,0,0,1],[1,0,0,1,1],[1,1,1,1,1]]'::jsonb, '{"x":1,"y":2,"dir":1}'::jsonb, '{"x":3,"y":1}'::jsonb, 5, null, null, '[]'::jsonb, 'Girar solo rota al robot, no lo mueve.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (4, 2, 'La Serpiente', 'Combina giros y pasos. Izquierda, derecha... ¡No te marees!', 'Giros', '[[1,1,1,1,1],[1,0,0,0,1],[1,1,1,0,1],[1,0,0,0,1],[1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":1,"y":3}'::jsonb, 8, null, null, '[]'::jsonb, 'Izquierda, luego derecha. Sigue el camino.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (5, 2, 'Media Vuelta', 'Te has metido en un callejón sin salida. Da media vuelta (gira dos veces) para salir.', 'Giros', '[[1,1,1,1,1],[0,0,0,0,1],[1,1,1,1,1]]'::jsonb, '{"x":3,"y":1,"dir":2}'::jsonb, '{"x":0,"y":1}'::jsonb, 5, null, null, '[]'::jsonb, 'Dos giros a la misma dirección dan media vuelta.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (6, 3, 'Trabajo Manual', '¿Notas que repites lo mismo? Avanzar, Girar, Avanzar, Girar... Hazlo paso a paso esta vez.', 'Patrones', '[[1,1,1,1,1,1],[1,1,1,0,0,1],[1,1,0,0,1,1],[1,0,0,1,1,1],[1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":3,"dir":1}'::jsonb, '{"x":4,"y":1}'::jsonb, 9, null, null, '[]'::jsonb, 'Identifica la secuencia que se repite.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (7, 3, 'Automatización', '¡Ahora usa el botón BUCLE 🔴! Escribe el patrón UNA vez y repítelo 3 veces.', 'Bucles', '[[1,1,1,1,1,1],[1,1,1,0,0,1],[1,1,0,0,1,1],[1,0,0,1,1,1],[1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":3,"dir":1}'::jsonb, '{"x":4,"y":1}'::jsonb, 6, null, null, '[]'::jsonb, 'Arrastra el bloque rojo (Bucle) y pon comandos dentro.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (8, 3, 'El Corredor Infinito', '8 pasos son muchos bloques... Usa un bucle para caminar todo el pasillo con una sola orden.', 'Bucles', '[[1,1,1,1,1,1,1,1,1,1],[1,0,0,0,0,0,0,0,0,1],[1,1,1,1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":8,"y":1}'::jsonb, 2, null, null, '[]'::jsonb, 'Usa un Bucle(8) con un "Avanzar" dentro.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (9, 4, 'La Puerta Cerrada', 'El camino está bloqueado 🔒. La llave 🔑 cambia las reglas: tómala para poder pasar.', 'Condicionales', '[[1,1,1,1,1,1,1],[1,0,2,0,3,0,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":5,"y":1}'::jsonb, 5, null, null, '[]'::jsonb, 'No puedes pasar la puerta sin la llave. Ve por ella primero.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (10, 4, 'El Recado', 'Divide el problema: 1. Ve por la llave. 2. Regresa a la puerta.', 'Condicionales', '[[1,1,1,1,1,1,1,1],[1,3,3,0,0,0,2,1],[1,1,1,1,1,1,1,1]]'::jsonb, '{"x":3,"y":1}'::jsonb, '{"x":1,"y":1}'::jsonb, 10, 15, 20, '[]'::jsonb, 'Primero ve a la llave (izquierda), luego vuelve a la puerta (derecha).', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (11, 5, 'Teletransporte', 'Los caminos no siempre son rectos. Entra al portal 🌀 para saltar los muros.', 'Portales', '[[1,1,1,1,1,1],[1,0,4,1,4,1],[1,0,1,1,0,1],[1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":4,"y":2}'::jsonb, 3, null, null, '[]'::jsonb, 'Los portales azules están conectados. Entra en uno para salir por el otro.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (12, 5, 'El Laberinto Roto', 'Un camino está roto. Analiza el mapa antes de programar y encuentra la ruta segura.', 'Debugging', '[[1,1,1,1,1,1,1],[1,0,0,1,0,0,1],[1,0,1,1,1,0,1],[1,0,0,0,0,0,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":2}'::jsonb, '{"x":5,"y":1}'::jsonb, 12, null, null, '[]'::jsonb, 'El camino de arriba está roto. Busca la ruta alternativa por abajo.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (13, 5, 'Reuniendo Conceptos', 'Bucles y Portales. Usa el bucle para llegar al portal rápidamente.', 'Avanzado', '[[1,1,1,1,1,1,1,1,1],[1,0,0,0,0,4,1,4,1],[1,1,1,1,1,1,1,0,1],[1,1,1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":7,"y":2}'::jsonb, 5, null, null, '[]'::jsonb, 'Usa "Avanzar" dentro de un bucle para llegar rápido al portal.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (14, 5, 'El Algoritmo Maestro', 'EXAMEN FINAL: Llave, Puerta y Portales. ¡Demuestra que eres un Code Hero!', 'Boss', '[[1,1,1,1,1,1,1],[1,0,2,1,0,0,1],[1,0,1,1,1,3,1],[1,4,0,0,0,4,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":5,"y":1}'::jsonb, 15, null, null, '[]'::jsonb, 'Planifica: 1. Llave, 2. Portal, 3. Puerta.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (15, 6, 'El Bucle Infinito', 'BUG DETECTADO: El bucle se repite demasiadas veces y choca. Ajusta el contador.', 'Debugging', '[[1,1,1,1,1,1,1],[1,0,0,0,0,1,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":4,"y":1}'::jsonb, 2, null, null, '[{"cmds":["moveForward"],"type":"loop","count":10}]'::jsonb, 'El bucle se repite 10 veces, pero solo hay espacio para menos pasos.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (16, 6, 'El Paso Olvidado', 'BUG DETECTADO: El robot se queda corto. Le falta una instrucción final.', 'Debugging', '[[1,1,1,1,1,1],[1,0,0,0,0,1],[1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":4,"y":1}'::jsonb, 4, null, null, '["moveForward","moveForward"]'::jsonb, 'El robot se detiene antes de la meta. Añade un paso más.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (17, 6, 'Giro Incorrecto', 'BUG DETECTADO: El robot gira a la izquierda, pero el camino es a la derecha.', 'Debugging', '[[1,1,1,1,1,1],[1,0,0,1,1,1],[1,1,0,0,0,1],[1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1}'::jsonb, '{"x":4,"y":2}'::jsonb, 5, 15, 20, '["moveForward","moveForward","turnLeft","moveForward","moveForward"]'::jsonb, 'El robot gira al lado equivocado. Corrige la dirección.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (18, 6, 'Código Espagueti', 'OPTIMIZACIÓN: Este código funciona, pero es muy largo y desordenado. Usa un Bucle para limpiarlo.', 'Refactor', '[[1,1,1,1,1,1,1,1],[1,0,0,0,0,0,0,1],[1,1,1,1,1,1,1,1]]'::jsonb, '{"x":1,"y":1,"dir":1}'::jsonb, '{"x":6,"y":1}'::jsonb, 2, null, null, '["moveForward","moveForward","moveForward","moveForward","moveForward"]'::jsonb, 'Reemplaza los 5 bloques "Avanzar" por un solo Bucle(5).', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    INSERT INTO public.levels (id, phase_id, title, description, type, map, start_pos, end_pos, perfect_score, stars_2_threshold, stars_1_threshold, start_code, hint, difficulty) VALUES 
    (19, 6, 'Acceso Denegado', 'ERROR DE SEGURIDAD: Intentando abrir la puerta sin la llave. Modifica la ruta para recoger la llave primero.', 'Debugging', '[[1,1,1,1,1,1,1],[1,2,0,1,3,0,1],[1,0,0,0,0,1,1],[1,1,1,1,1,1,1]]'::jsonb, '{"x":2,"y":2,"dir":1}'::jsonb, '{"x":5,"y":1}'::jsonb, 7, 15, 20, '["moveForward","moveForward","turnLeft","moveForward"]'::jsonb, 'La puerta está cerrada. Desvíate a la casilla (2,2) para coger la llave.', 1) 
    ON CONFLICT (id) DO UPDATE SET map = EXCLUDED.map, start_pos = EXCLUDED.start_pos, end_pos = EXCLUDED.end_pos, perfect_score = EXCLUDED.perfect_score, hint = EXCLUDED.hint;
    ALTER SEQUENCE public.levels_id_seq RESTART WITH 20;

    -- ============ [ END ] SEED DATA (COPY FROM ADMIN) ============
END;
$$;

-- HELPER PROCEDURE (To make upserts cleaner above)
create or replace function public.upsert_level_by_title(
    p_phase_id bigint, p_title text, p_type text, p_desc text, p_map jsonb, p_start jsonb, p_end jsonb, p_perfect int, p_start_code jsonb default '[]'::jsonb
) returns void language plpgsql as $$
BEGIN
    if exists (select 1 from levels where title = p_title) then
        update levels set 
            phase_id = p_phase_id, type = p_type, description = p_desc, map = p_map, 
            start_pos = p_start, end_pos = p_end, perfect_score = p_perfect, start_code = p_start_code
        where title = p_title;
    else
        insert into levels (phase_id, title, type, description, map, start_pos, end_pos, perfect_score, start_code)
        values (p_phase_id, p_title, p_type, p_desc, p_map, p_start, p_end, p_perfect, p_start_code);
    end if;
END;
$$;

-- Grant permissions
grant execute on function public.reset_level_data to authenticated;
grant execute on function public.upsert_level_by_title to authenticated;

-- Run it immediately for the install
select public.reset_level_data();  

SELECT 'CodeHero Database Installed & Seeded Successfully' as status;
